-- Eliminar FKs de Doctores
ALTER TABLE pyd_Doctores DROP CONSTRAINT FK_DOCTOR_PERSONA;
ALTER TABLE pyd_Doctores DROP CONSTRAINT FK_DOCTOR_AREA;
ALTER TABLE pyd_Doctores DROP CONSTRAINT FK_DOCTOR_TURNO;

-- Eliminar FKs de Enfermeras
ALTER TABLE pyd_Enfermeras DROP CONSTRAINT FK_ENFERMERA_PERSONA;
ALTER TABLE pyd_Enfermeras DROP CONSTRAINT FK_ENFERMERA_AREA;
ALTER TABLE pyd_Enfermeras DROP CONSTRAINT FK_ENFERMERA_TURNO;

-- Eliminar FKs de Pacientes
ALTER TABLE pyd_Pacientes DROP CONSTRAINT FK_PACIENTE_PERSONA;
-- ALTER TABLE pyd_Pacientes DROP CONSTRAINT FK_PACIENTE_HISTORIA; -- Se omite si no se pudo crear antes.

-- Eliminar FKs de Cuartos
ALTER TABLE pyd_Cuartos DROP CONSTRAINT FK_CUARTO_OCUPANTE;

-- Eliminar FKs de Areas
ALTER TABLE pyd_Areas DROP CONSTRAINT FK_AREA_DOCTOR_ENCARGADO;
ALTER TABLE pyd_Areas DROP CONSTRAINT FK_AREA_ENFERMERA_JEFE;

-- Eliminar FKs de Visitas
ALTER TABLE pyd_Visitas DROP CONSTRAINT FK_VISITA_HISTORIA;

-- Eliminar FKs de Citas
ALTER TABLE pyd_Citas DROP CONSTRAINT FK_CITA_PACIENTE;
ALTER TABLE pyd_Citas DROP CONSTRAINT FK_CITA_DOCTOR;