--primarias 
ALTER TABLE pyd_Personas ADD CONSTRAINT PK_PERSONA PRIMARY KEY (Numero_doc);
ALTER TABLE pyd_Cuartos ADD CONSTRAINT PK_CUARTOS PRIMARY KEY (N_Cuarto);
ALTER TABLE pyd_Areas ADD CONSTRAINT PK_AREAS PRIMARY KEY (Area);
ALTER TABLE pyd_Doctores ADD CONSTRAINT PK_DOCTORES PRIMARY KEY (Id_Doctor);
ALTER TABLE pyd_Enfermeras ADD CONSTRAINT PK_ENFERMERAS PRIMARY KEY (Id_Enfermera);
ALTER TABLE pyd_Pacientes ADD CONSTRAINT PK_PACIENTES PRIMARY KEY (Id_Paciente);
ALTER TABLE pyd_HistoriasClinicas ADD CONSTRAINT PK_HISTORIACLINICA PRIMARY KEY (Id_Historia);
ALTER TABLE pyd_Visitas ADD CONSTRAINT PK_VISITAS PRIMARY KEY (Id_Visita);
ALTER TABLE pyd_Turnos ADD CONSTRAINT PK_TURNOS PRIMARY KEY (Tipo_Turno);
ALTER TABLE pyd_Citas ADD CONSTRAINT PK_CITAS PRIMARY KEY (Id_Cita);
ALTER TABLE pyd_PQRS ADD CONSTRAINT PK_PQR PRIMARY KEY (Id_PQR);