CREATE TABLE Persona (
    Numero_doc NUMBER NOT NULL,
    Tipo_documento VARCHAR2(10) NOT NULL,
    primer_nombre VARCHAR2(50) NOT NULL,
    segundo_nombre VARCHAR2(50),
    primer_apellido VARCHAR2(50) NOT NULL,
    segundo_apellido VARCHAR2(50)
);


CREATE TABLE Cuartos (
    N_Cuarto NUMBER NOT NULL,
    Estado VARCHAR2(50) NOT NULL,
    Tipo_Cuarto VARCHAR2(50) NOT NULL,
    ocupante NUMBER
);


CREATE TABLE Areas (
    Id_Area NUMBER NOT NULL,
    especialidad VARCHAR2(100) NOT NULL,
    camas NUMBER NOT NULL,
    doctor_encargado NUMBER,
    enfermeria_jefe NUMBER
);


CREATE TABLE Doctores (
    Id_Doctor NUMBER NOT NULL,
    Especialidad VARCHAR2(100) NOT NULL,
    Area_Especialidad NUMBER,
    T_Turno NUMBER,
    Numero_Doc NUMBER NOT NULL
);


CREATE TABLE Enfermeras (
    Id_Enfermera NUMBER NOT NULL,
    Area NUMBER,
    Especialidad VARCHAR2(100),
    Turno NUMBER,
    Numero_Doc NUMBER NOT NULL
);


CREATE TABLE Pacientes (
    Id_HojaCl NUMBER NOT NULL,
    Id_Eps NUMBER NOT NULL,
    Eps VARCHAR2(100) NOT NULL,
    Numero_Doc NUMBER NOT NULL
);

CREATE TABLE HistoriasClinicas (
    Id_Historia NUMBER NOT NULL,
    Eps VARCHAR2(100) NOT NULL,
    Nombre_Eps VARCHAR2(100) NOT NULL
);

CREATE TABLE Visitas (
    Id_Visita NUMBER NOT NULL,
    Fecha DATE NOT NULL,
    Sintomas VARCHAR2(255) NOT NULL,
    Examen VARCHAR2(255),
    Diagnostico VARCHAR2(255) NOT NULL,
    Tratamiento VARCHAR2(255) NOT NULL,
    Id_Historia NUMBER NOT NULL
);

CREATE TABLE Turnos (
    Tipo_Turno NUMBER NOT NULL,
    Nombre_Turno VARCHAR2(50) NOT NULL,
    Inicia DATE NOT NULL,
    Acaba DATE NOT NULL
);

CREATE TABLE Citas (
    Id_Cita NUMBER NOT NULL,
    Id_Paciente NUMBER NOT NULL,
    Hora_Cita DATE NOT NULL,
    Fecha_Cita DATE NOT NULL,
    Id_Doctor NUMBER NOT NULL,
    Diagnostico VARCHAR2(255),
    Estado_Cita VARCHAR2(50) NOT NULL
);

CREATE TABLE PQR (
    Id_PQR NUMBER NOT NULL,
    Descripcion VARCHAR2(255) NOT NULL,
    Tema VARCHAR2(100),
    Cadena VARCHAR2(255)
);

ALTER TABLE Persona ADD CONSTRAINT PK_PERSONA PRIMARY KEY (Numero_doc);
ALTER TABLE Cuartos ADD CONSTRAINT PK_CUARTOS PRIMARY KEY (N_Cuarto);
ALTER TABLE Areas ADD CONSTRAINT PK_AREAS PRIMARY KEY (Id_Area);
ALTER TABLE Doctores ADD CONSTRAINT PK_DOCTORES PRIMARY KEY (Id_Doctor);
ALTER TABLE Enfermeras ADD CONSTRAINT PK_ENFERMERAS PRIMARY KEY (Id_Enfermera);
ALTER TABLE Pacientes ADD CONSTRAINT PK_PACIENTES PRIMARY KEY (Id_HojaCl);
ALTER TABLE HistoriasClinicas ADD CONSTRAINT PK_HISTORIACLINICA PRIMARY KEY (Id_Historia);
ALTER TABLE Visitas ADD CONSTRAINT PK_VISITAS PRIMARY KEY (Id_Visita);
ALTER TABLE Turnos ADD CONSTRAINT PK_TURNOS PRIMARY KEY (Tipo_Turno);
ALTER TABLE Citas ADD CONSTRAINT PK_CITAS PRIMARY KEY (Id_Cita);
ALTER TABLE PQR ADD CONSTRAINT PK_PQR PRIMARY KEY (Id_PQR);

ALTER TABLE Doctores ADD CONSTRAINT FK_DOCTOR_PERSONA
FOREIGN KEY (Id_Doctor) REFERENCES Persona (Numero_doc);

ALTER TABLE Enfermeras ADD CONSTRAINT FK_ENFERMERA_PERSONA
FOREIGN KEY (Id_Enfermera) REFERENCES Persona (Numero_doc);

ALTER TABLE Pacientes ADD CONSTRAINT FK_PACIENTE_PERSONA
FOREIGN KEY (Numero_Doc) REFERENCES Persona (Numero_doc);

ALTER TABLE Cuartos ADD CONSTRAINT FK_CUARTO_OCUPANTE
FOREIGN KEY (ocupante) REFERENCES Persona (Numero_doc);

ALTER TABLE Areas ADD CONSTRAINT FK_AREA_DOCTOR_ENCARGADO
FOREIGN KEY (doctor_encargado) REFERENCES Doctores (Id_Doctor);

ALTER TABLE Areas ADD CONSTRAINT FK_AREA_ENFERMERA_JEFE
FOREIGN KEY (enfermeria_jefe) REFERENCES Enfermeras (Id_Enfermera);

ALTER TABLE Doctores ADD CONSTRAINT FK_DOCTOR_AREA
FOREIGN KEY (Area_Especialidad) REFERENCES Areas (Id_Area);

ALTER TABLE Doctores ADD CONSTRAINT FK_DOCTOR_TURNO
FOREIGN KEY (T_Turno) REFERENCES Turnos (Tipo_Turno);

ALTER TABLE Enfermeras ADD CONSTRAINT FK_ENFERMERA_AREA
FOREIGN KEY (Area) REFERENCES Areas (Id_Area);

ALTER TABLE Enfermeras ADD CONSTRAINT FK_ENFERMERA_TURNO
FOREIGN KEY (Turno) REFERENCES Turnos (Tipo_Turno);

ALTER TABLE Pacientes ADD CONSTRAINT FK_PACIENTE_HISTORIA
FOREIGN KEY (Id_HojaCl) REFERENCES HistoriasClinicas (Id_Historia);

ALTER TABLE Visitas ADD CONSTRAINT FK_VISITA_HISTORIA
FOREIGN KEY (Id_Historia) REFERENCES HistoriasClinicas (Id_Historia);

ALTER TABLE Citas ADD CONSTRAINT FK_CITA_PACIENTE
FOREIGN KEY (Id_Paciente) REFERENCES Persona (Numero_doc);

ALTER TABLE Citas ADD CONSTRAINT FK_CITA_DOCTOR
FOREIGN KEY (Id_Doctor) REFERENCES Doctores (Id_Doctor);