
DEFINE ROLE_DOCTOR          = 'ROL_DOCTOR_CLINICA';
DEFINE ROLE_ADMINISTRATIVO  = 'ROL_ADMIN_CLINICA';
DEFINE ROLE_ENFERMERA       = 'ROL_ENFERMERA_CLINICA';
DEFINE ROLE_PACIENTE        = 'ROL_PACIENTE_CLINICA';


CREATE ROLE &ROLE_DOCTOR;
CREATE ROLE &ROLE_ADMINISTRATIVO;
CREATE ROLE &ROLE_ENFERMERA;
CREATE ROLE &ROLE_PACIENTE;

GRANT EXECUTE ON PKG_DOCTOR_ACCESS TO &ROLE_DOCTOR;

GRANT EXECUTE ON PKG_ADMIN_ACCESS TO &ROLE_ADMINISTRATIVO;

GRANT SELECT ON pyd_Pacientes TO &ROLE_DOCTOR;
GRANT SELECT ON pyd_HistoriasClinicas TO &ROLE_DOCTOR;

GRANT SELECT ON pyd_Personas TO &ROLE_ADMINISTRATIVO;
GRANT SELECT ON pyd_Turnos TO &ROLE_ADMINISTRATIVO;


COMMIT;


UNDEFINE ROLE_DOCTOR
UNDEFINE ROLE_ADMINISTRATIVO
UNDEFINE ROLE_ENFERMERA
UNDEFINE ROLE_PACIENTE