--primarias 
ALTER TABLE pyd_Personas ADD CONSTRAINT PK_PERSONA PRIMARY KEY (Numero_doc);
ALTER TABLE pyd_Cuartos ADD CONSTRAINT PK_CUARTOS PRIMARY KEY (N_Cuarto);
ALTER TABLE pyd_Areas ADD CONSTRAINT PK_AREAS PRIMARY KEY (Area);
ALTER TABLE pyd_Doctores ADD CONSTRAINT PK_DOCTORES PRIMARY KEY (Id_Doctor);
ALTER TABLE pyd_Enfermeras ADD CONSTRAINT PK_ENFERMERAS PRIMARY KEY (Id_Enfermera);
ALTER TABLE pyd_Pacientes ADD CONSTRAINT PK_PACIENTES PRIMARY KEY (Id_Paciente);
ALTER TABLE pyd_HistoriasClinicas ADD CONSTRAINT PK_HISTORIACLINICA PRIMARY KEY (Id_Historia);
ALTER TABLE pyd_Visitas ADD CONSTRAINT PK_VISITAS PRIMARY KEY (Id_Visita);
ALTER TABLE pyd_Turnos ADD CONSTRAINT PK_TURNOS PRIMARY KEY (Tipo_Turno);
ALTER TABLE pyd_Citas ADD CONSTRAINT PK_CITAS PRIMARY KEY (Id_Cita);
ALTER TABLE pyd_PQRS ADD CONSTRAINT PK_PQR PRIMARY KEY (Id_PQR);

--foraneas 
ALTER TABLE pyd_Doctores ADD CONSTRAINT FK_DOCTOR_PERSONA
FOREIGN KEY (Id_Doctor) REFERENCES pyd_Personas (Numero_doc);

ALTER TABLE pyd_Enfermeras ADD CONSTRAINT FK_ENFERMERA_PERSONA
FOREIGN KEY (Id_Enfermera) REFERENCES pyd_Personas (Numero_doc);

ALTER TABLE pyd_Pacientes ADD CONSTRAINT FK_PACIENTE_PERSONA
FOREIGN KEY (Numero_Doc) REFERENCES pyd_Personas (Numero_doc);

ALTER TABLE pyd_Cuartos ADD CONSTRAINT FK_CUARTO_OCUPANTE
FOREIGN KEY (ocupante) REFERENCES pyd_Personas (Numero_doc);

ALTER TABLE pyd_Areas ADD CONSTRAINT FK_AREA_DOCTOR_ENCARGADO
FOREIGN KEY (doctor_encargado) REFERENCES pyd_Doctores (Id_Doctor);

ALTER TABLE pyd_Areas ADD CONSTRAINT FK_AREA_ENFERMERA_JEFE
FOREIGN KEY (enfermeria_jefe) REFERENCES pyd_Enfermeras (Id_Enfermera);

ALTER TABLE pyd_Doctores ADD CONSTRAINT FK_DOCTOR_AREA
FOREIGN KEY (Area_Especialidad) REFERENCES pyd_Areas (Area);

ALTER TABLE pyd_Doctores ADD CONSTRAINT FK_DOCTOR_TURNO
FOREIGN KEY (T_Turno) REFERENCES pyd_Turnos (Tipo_Turno);

ALTER TABLE pyd_Enfermeras ADD CONSTRAINT FK_ENFERMERA_AREA
FOREIGN KEY (Area) REFERENCES pyd_Areas (Area);

ALTER TABLE pyd_Enfermeras ADD CONSTRAINT FK_ENFERMERA_TURNO
FOREIGN KEY (Turno) REFERENCES pyd_Turnos (Tipo_Turno);

ALTER TABLE pyd_Pacientes ADD CONSTRAINT FK_PACIENTE_HISTORIA
FOREIGN KEY (Id_paciente) REFERENCES pyd_HistoriasClinicas (Id_Historia);

ALTER TABLE pyd_Visitas ADD CONSTRAINT FK_VISITA_HISTORIA
FOREIGN KEY (Id_Historia) REFERENCES pyd_HistoriasClinicas (Id_Historia);

ALTER TABLE pyd_Citas ADD CONSTRAINT FK_CITA_PACIENTE
FOREIGN KEY (Id_Paciente) REFERENCES pyd_Personas (Numero_doc);

ALTER TABLE pyd_Citas ADD CONSTRAINT FK_CITA_DOCTOR
FOREIGN KEY (Id_Doctor) REFERENCES pyd_Doctores (Id_Doctor);